"""Versions of the screening prompt, recorded on every source_screenings row.

A screening's identity is (source, taste_version, screen_rules_sha256,
screening_prompt_version). The prompt version is what lets a prediction be
traced to the exact instructions that produced it, and what stops two prompts
with different authority rules from being mistaken for one another.

LEGACY (1): the peer-authority prompt. Taste and permanent rules were presented
as equals, with no statement of which governs. Every screening stored before
prompt provenance existed was produced by this prompt, so migration 18 labels
all existing rows with it. No prompt version was recorded before this change.
Historical only -- no code ever requests this as the current prompt.

AUTHORITY_ORDERED (2): the authority-ordered prompt. Permanent rules are
labelled authoritative and outrank the inferred taste, but it has no explicit
INVESTIGATE_NOW/WATCH/PASS classification guidance. This produced every
screening behind the completed Taste v3 holdout evaluation -- historical only.
Superseded as CURRENT by version 3 when the WATCH/PASS guidance below was
added; those v3 holdout screenings are NOT rewritten or regenerated by that
change, so the completed evaluation stays reproducible exactly as it ran.

CURRENT (3): the authority-ordered prompt PLUS explicit WATCH/PASS
classification guidance -- see ideascout/shadow.py. The guidance materially
changed the screening prompt's instructions (not just its authority framing),
so it gets its own version rather than silently reusing version 2's identity.
"""

LEGACY_SCREENING_PROMPT_VERSION = 1
AUTHORITY_ORDERED_SCREENING_PROMPT_VERSION = 2
CURRENT_SCREENING_PROMPT_VERSION = 3

SCREENING_PROMPT_DESCRIPTIONS = {
    LEGACY_SCREENING_PROMPT_VERSION: "legacy peer-authority prompt",
    AUTHORITY_ORDERED_SCREENING_PROMPT_VERSION: "authority-ordered prompt (permanent rules outrank taste)",
    CURRENT_SCREENING_PROMPT_VERSION: "authority-ordered prompt + explicit WATCH/PASS semantics",
}
